### ISSUE TITLE
mulle-lldb shows errors on startup on darwin

### ISSUE THREAD

**Issue by mulle-nat** [Codeon-GmbH/mulle-lldb#6]
It hangs immediately after run: How to reproduce:

```
b main
run 
```

Should check, if even the regular lldb works.

**Comment by mulle-nat** [comment]
Actually that probably happened, because the binary wasn't properly signed. 
The actual 6.0.0.3 built for homebrew works, but emits spurious warnings like this on start:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

Which is probably python related. (#3 contains a possible fix)

* [python2 breaking lldb on osx](https://github.com/Homebrew/homebrew-core/issues/2730)
* [rust-lldb throws Python errors macOS 10.12.2](https://github.com/rust-lang/rust/issues/38380)
* [Debugger is not working on OSX 10.12.3 with QT 5.9 and QT Creator 4.4.1](https://forum.qt.io/topic/85010/debugger-is-not-working-on-osx-10-12-3-with-qt-5-9-and-qt-creator-4-4-1)
